Repository TEIC/TEI, pull requests merged in 2022-04, with the labels that each got.

#2193 deprecate <altIdent> in bizarre places
  P5/Source/Guidelines/en/AI-AnalyticMechanisms.xml
  P5/Source/Guidelines/en/CC-LanguageCorpora.xml
  P5/Source/Guidelines/en/CE-CertaintyResponsibility.xml
  P5/Source/Guidelines/en/CO-CoreElements.xml
  P5/Source/Guidelines/en/DI-PrintDictionaries.xml
  P5/Source/Guidelines/en/DR-PerformanceTexts.xml
  P5/Source/Guidelines/en/DS-DefaultTextStructure.xml
  P5/Source/Guidelines/en/FS-FeatureStructures.xml
  P5/Source/Guidelines/en/FT-TablesFormulaeGraphics.xml
  P5/Source/Guidelines/en/GD-GraphsNetworksTrees.xml
  P5/Source/Guidelines/en/HD-Header.xml
  P5/Source/Guidelines/en/MS-ManuscriptDescription.xml
  P5/Source/Guidelines/en/ND-NamesDates.xml
  P5/Source/Guidelines/en/PH-PrimarySources.xml
  P5/Source/Guidelines/en/SA-LinkingSegmentationAlignment.xml
  P5/Source/Guidelines/en/ST-Infrastructure.xml
  P5/Source/Guidelines/en/TC-CriticalApparatus.xml
  P5/Source/Guidelines/en/TD-DocumentationElements.xml
  P5/Source/Guidelines/en/TS-TranscriptionsofSpeech.xml
  P5/Source/Guidelines/en/VE-Verse.xml
  P5/Source/Guidelines/en/WD-NonStandardCharacters.xml
  P5/Source/Specs/altIdent.xml
  P5/Source/Specs/moduleSpec.xml
  P5/p5odds.odd
Labels: Deprecation, TEI: Guidelines & Documentation, TEI: Schema, CouncilResponsibility

#2204 Address #2185 by restricting anyURI to not have spaces
  P5/Source/Guidelines/en/TC-CriticalApparatus.xml
  P5/Source/Specs/adminInfo.xml
  P5/Source/Specs/citeData.xml
  P5/Source/Specs/teidata.namespace.xml
  P5/Source/Specs/teidata.namespaceOrName.xml
  P5/Source/Specs/teidata.point.xml
  P5/Source/Specs/teidata.pointer.xml
  P5/Source/Specs/zone.xml
  P5/Test/testbasic.xml
  P5/Test/testtranscr.xml
Labels: Type: Bug, TEI: Schema, CouncilResponsibility

#2235 Issue 2106: broken links to non-English bibliography entries
  P5/Source/Guidelines/en/BIB-Bibliography.xml
  P5/Source/Specs/caesura.xml
  P5/Source/Specs/castGroup.xml
  P5/Source/Specs/castItem.xml
  P5/Source/Specs/div.xml
  P5/Source/Specs/div2.xml
  P5/Source/Specs/div3.xml
  P5/Source/Specs/div4.xml
  P5/Source/Specs/epigraph.xml
  P5/Source/Specs/front.xml
  P5/Source/Specs/prologue.xml
  P5/Source/Specs/role.xml
  P5/Source/Specs/sp.xml
  P5/Source/Specs/space.xml
  P5/Source/Specs/speaker.xml
Labels: i18n

#2266 detest fix
  P5/Test/detest.odd
  P5/Test/detest.xml
  P5/Test/expected-results/detest.log
Labels: TEI: Build Process

#2188 Fix #2187, I hope
  P5/Source/Guidelines/en/TD-DocumentationElements.xml
  P5/Source/Specs/constraintSpec.xml
  P5/Source/Specs/elementSpec.xml
  P5/Utilities/subset.xsl
Labels: Type: Bug, TEI: Schema, TEI: Build Process, CouncilResponsibility

#2278 de-classify type= of att.interpLike
  P5/Source/Specs/att.interpLike.xml
  P5/Source/Specs/interp.xml
  P5/Source/Specs/interpGrp.xml
  P5/Source/Specs/span.xml
  P5/Source/Specs/spanGrp.xml
Labels: Type: Bug, Priority: Release Blocker, CouncilResponsibility

#2290 Fix apparent copy-paste error in ident= of a constraint specification
  P5/Exemplars/tei_jtei.odd
Labels: TEI: Schema: jTEI, TEI: Exemplars
