Repository TEIC/TEI, pull requests merged in 2023-05, with the labels that each got.

#2417 give footer (and heading) “P5”
  P5/Source/guidelines-en.xml
  P5/Source/guidelines-fr.xml
  P5/Utilities/guidelines.xsl.model
Labels: TEI: Guidelines & Documentation, TEI: Build Process

#2430 Update att.gaijiProp.xml
  P5/Source/Specs/att.gaijiProp.xml
Labels: TEI: Guidelines & Documentation, CouncilResponsibility

#2416 guidelines.xsl generation update
  P5/Makefile
  P5/Utilities/guidelines-latex.xsl
  P5/Utilities/guidelines-print.xsl
  P5/Utilities/guidelines.xsl.model
  P5/Utilities/guidelines_model_2_executable.xslt
Labels: TEI: Build Process

#2424 Updated the title of 2.2.8 for #2415
  P5/Source/Guidelines/en/HD-Header.xml
Labels: Priority: Low, TEI: Guidelines & Documentation

#2393 constrain att.translatable elements when used in the Guidelines
  P5/Source/Specs/altIdentifier.xml
  P5/Source/Specs/att.citing.xml
  P5/Source/Specs/availability.xml
  P5/Source/Specs/divGen.xml
  P5/Source/Specs/extent.xml
  P5/Source/Specs/listRelation.xml
  P5/Source/Specs/nym.xml
  P5/Source/Specs/oRef.xml
  P5/Source/Specs/q.xml
  P5/Source/Specs/speaker.xml
  P5/Test/expected-results/detest_odd_schematron.log
  P5/p5odds.odd
  P5/spec_lists.json
Labels: CouncilResponsibility, i18n
