Repository TEIC/TEI, pull requests merged in 2025-03, with the labels that each got.

#2680 remove contextless schematron deprecation
  P5/Source/Specs/constraintDecl.xml
  P5/Source/Specs/constraintSpec.xml
  P5/Test/expected-results/detest_odd_schematron.log
Labels: Priority: High

#2682 fix `@ident` of `<remarks>`, at least partially
  P5/Source/Specs/remarks.xml
Labels: TEI: ODD, CouncilResponsibility

#2689 Update to content model of 'ography'-elements
  P5/Source/Specs/event.xml
  P5/Source/Specs/org.xml
  P5/Source/Specs/person.xml
  P5/Source/Specs/place.xml
Labels: TEI: Guidelines & Documentation
