Repository TEIC/TEI, pull requests merged in 2025-05, with the labels that each got.

#2692 Move note content handling into the event
  P5/guidelines.css
  P5/webnav/popupFootnotes.js
Labels: Type: Bug, Priority: High, TEI: Build Process

#2693 improve encoding of `<list>`s
  P5/Source/Guidelines/en/AB-About.xml
  P5/Source/Guidelines/en/TC-CriticalApparatus.xml
  P5/Source/Guidelines/en/TD-DocumentationElements.xml
Labels: Priority: Low, TEI: Guidelines & Documentation

#2600 WIP: remove mobi from the generated outputs; close #2574
  Documents/Editing/Jenkins/jobs/Guidelines-Link-Check/linkchecker.xsl
  Documents/Editing/Jenkins/jobs/Guidelines-Link-Check/linkcheckerrcalphabeta
  Documents/Editing/Jenkins/jobs/Guidelines-Link-Check/linkcheckerrcrelease
  Documents/howtomakep5.xml
  P5/Makefile
  P5/Utilities/guidelines.xsl.model
  P5/debian-tei-p5-doc/debian/rules
  P5/webnav/icons/e-book-icons/license.txt
  P5/webnav/icons/e-book-icons/mdh_mobi_doc.svg
  P5/webnav/icons/e-book-icons/mdh_mobi_doc_32x32.png
  P5/webnav/icons/e-book-icons/mdh_mobi_doc_48x48.png
  P5/webnav/icons/e-book-icons/mdh_mobi_doc_64x64.png
Labels: Priority: High, Status: Needs Discussion
