Repository TEIC/TEI, pull requests merged in 2025-01, with the labels that each got.

#2633 Updated specs for `<line>` and `<lb>`
  P5/Source/Specs/lb.xml
  P5/Source/Specs/line.xml
Labels: Status: Go, TEI: Guidelines & Documentation

#2579 fix description by restoring lost value
  P5/Source/Specs/gap.xml
Labels: Status: Go

#2634 Replaced 'break' with 'beginning' for page|line|column|gathering in Guidelines and Specs
  P5/Source/Guidelines/en/CH-LanguagesCharacterSets.xml
  P5/Source/Guidelines/en/CO-CoreElements.xml
  P5/Source/Guidelines/en/DI-PrintDictionaries.xml
  P5/Source/Guidelines/en/DS-DefaultTextStructure.xml
  P5/Source/Guidelines/en/FT-TablesFormulaeGraphics.xml
  P5/Source/Guidelines/en/HD-Header.xml
  P5/Source/Guidelines/en/NH-Non-hierarchical.xml
  P5/Source/Guidelines/en/PH-PrimarySources.xml
  P5/Source/Guidelines/en/SG-GentleIntroduction.xml
  P5/Source/Guidelines/en/WD-NonStandardCharacters.xml
  P5/Source/Specs/att.breaking.xml
  P5/Source/Specs/att.edition.xml
  P5/Source/Specs/att.milestoneUnit.xml
  P5/Source/Specs/cb.xml
  P5/Source/Specs/gb.xml
  P5/Source/Specs/param.xml
  P5/Source/Specs/pb.xml
Labels: Status: Go

#2662 Implement @hcayless solution #1 for issue @2246 — do not test `@spanTo` across files
  P5/Source/Specs/att.spanning.xml
  P5/Test/detest.xml
  P5/Test/expected-results/detest_xml_schematron.log
Labels: TEI: Schematron

#2660 use `<constraintDecl>` in Guidelines and tei_customization, and add CMC to French Guidelines
  P5/Source/Specs/TEI.xml
  P5/Source/guidelines-en.xml
  P5/Source/guidelines-fr.xml
  P5/Utilities/TEI-to-tei_customization.xslt
Labels: Type: Bug, Priority: High, TEI: Schematron
